apiVersion: apps/v1
kind: Deployment
metadata:
  name: github-actions-runner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: github-actions-runner
  template:
    metadata:
      labels:
        app: github-actions-runner
    spec:
      containers:
        - name: github-actions-runner
          image: summerwind/actions-runner-controller:v0.27.6
          env:
            - name: RUNNER_NAME
              value: "github-actions-runner"
            - name: RUNNER_TOKEN
              valueFrom:
                secretKeyRef:
                  name: github-actions-runner-secret
                  key: token
            - name: RUNNER_REPO
              value: "https://github.com/Bazzako/SemArb4-CD-und-Camunda-BPM"
