name: Deploy Camunda Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: arc-runner-set

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Camunda Files
      run: |
            #!/bin/bash

            # Camunda Server URL
            SERVER_URL="http://10.0.24.77:30000/engine-rest/deployment/create"

            # URLs der .form- und .bpmn-Dateien im Git-Repository (Raw-URLs)
            FILES=(
                "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Grundgeruest.bpmn"
                "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Abholung.form"
                "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Anmeldeformular.form"
                "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Datenerfassung.form"
                "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Datensicherung.form"
                "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Defektanalyse.form"
            )

            # Iteriere über die Dateien und führe den curl-Befehl aus
            for URL in "${FILES[@]}"
            do
                echo "Lade Datei hoch: $URL"

                # Extrahiere den Dateinamen ohne die Erweiterung (.form oder .bpmn)
                FILENAME=$(basename "$URL" .form)
                FILENAME=${FILENAME%.bpmn}  # Entferne .bpmn, falls die Datei eine .bpmn-Datei ist

                # Herunterladen der Datei und Speichern unter dem Namen ohne die Erweiterung
                curl -s -o "$FILENAME" "$URL"

                # Datei an Camunda hochladen
                curl --location "$SERVER_URL" \
                    --header 'Content-Type: multipart/form-data' \
                    --form "upload=@$FILENAME"

                # Temporäre Datei löschen
                rm "$FILENAME"

                sleep 1
            done

            echo "Alle Dateien wurden erfolgreich hochgeladen."




