name: Deploy Camunda Files

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: arc-runner-set

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Camunda Files
      run: |
                #!/bin/bash

                # Camunda Server URL
                SERVER_URL="http://10.0.24.77:30000/engine-rest/deployment/create"

                # URLs der .form-Dateien im Git-Repository (Raw-URLs)
                FILES=(
                    "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Abholung.form"
                    "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Anmeldeformular.form"
                    "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Datenerfassung.form"
                    "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Datensicherung.form"
                    "https://raw.githubusercontent.com/Bazzako/SemArb4-CD-und-Camunda-BPM/main/processes/Defektanalyse.form"
                )

                # Iteriere über die Dateien und führe den curl-Befehl aus
                for URL in "${FILES[@]}"
                do
                    echo "Lade Datei hoch: $URL"

                    # Herunterladen der Datei
                    TEMP_FILE=$(mktemp)
                    curl -s -o "$TEMP_FILE" "$URL"

                    # Datei an Camunda hochladen
                    curl --location "$SERVER_URL" \
                        --header 'Content-Type: multipart/form-data' \
                        --form "upload=@$TEMP_FILE"

                    # Temporäre Datei löschen
                    rm "$TEMP_FILE"

                    sleep 1
                done

                echo "Alle Dateien wurden erfolgreich hochgeladen."

