name: Deploy Camunda Files

on:
  push:
    paths:
      - 'processes/**'

jobs:
  deploy:
    runs-on: arc-runner-set

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Deploy Camunda Files
      run: |
        #!/bin/bash

        # Camunda Server URL
        SERVER_URL="http://10.0.24.77:30000/engine-rest/deployment/create"

        # Durchsuchen des Repositories nach allen Dateien im Verzeichnis "processes"
        echo "Durchsuche Repository nach Dateien im Verzeichnis 'processes'..."

        # Alle Dateien im "processes"-Verzeichnis herunterladen und hochladen
        files=$(find processes -type f)
        for file in $files; do
          echo "Lade Datei hoch: $file"

          # Raw-URL der Datei erstellen
          RAW_URL="https://raw.githubusercontent.com/${GITHUB_REPOSITORY}/main/$file"

          # Datei direkt an Camunda hochladen
          curl --location "$SERVER_URL" \
            --header 'Content-Type: multipart/form-data' \
            --form "upload=@$RAW_URL"
          
          sleep 1
        done

        echo "Alle Dateien wurden erfolgreich hochgeladen."
